#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# STEEX Scheduler - install.sh
# Reads enabled modes + schedules from config.yaml, writes cron entries.
# Discovers all modes dynamically from config (no hardcoded list).
# Usage:
#   scheduler/install.sh          # Install cron entries
#   scheduler/install.sh --show   # Preview without installing
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG="$SCRIPT_DIR/config.yaml"
VENV_PYTHON="$PROJECT_DIR/venv/bin/python"

MARKER_START="# STEEX-SCHEDULER-START"
MARKER_END="# STEEX-SCHEDULER-END"

SHOW_ONLY=false
if [ "${1:-}" = "--show" ]; then
    SHOW_ONLY=true
fi

# ---------------------------------------------------------------------------
# Dynamically discover all modes from config
# ---------------------------------------------------------------------------

MODES=$("$VENV_PYTHON" -c "
import yaml
with open('$CONFIG') as f:
    cfg = yaml.safe_load(f)
for mode in cfg.get('modes', {}):
    print(mode)
")

if [ -z "$MODES" ]; then
    echo "No modes found in config. Nothing to install."
    exit 0
fi

# ---------------------------------------------------------------------------
# Parse enabled modes and schedules from config
# ---------------------------------------------------------------------------

CRON_BLOCK="$MARKER_START
# Auto-generated by scheduler/install.sh - do not edit manually
SHELL=/bin/bash
# Keep Mac awake during market hours (3:55 AM PST, before first job)
55 3 * * 1-5 $SCRIPT_DIR/keep_awake.sh >> $SCRIPT_DIR/logs/cron_keep_awake.log 2>&1"

FOUND_ANY=false

while IFS= read -r MODE; do
    ENABLED=$("$VENV_PYTHON" -c "
import yaml
with open('$CONFIG') as f:
    cfg = yaml.safe_load(f)
print(cfg.get('modes', {}).get('$MODE', {}).get('enabled', False))
")
    if [ "$ENABLED" != "True" ] && [ "$ENABLED" != "true" ]; then
        continue
    fi

    SCHEDULE=$("$VENV_PYTHON" -c "
import yaml
with open('$CONFIG') as f:
    cfg = yaml.safe_load(f)
print(cfg.get('modes', {}).get('$MODE', {}).get('schedule', ''))
")
    if [ -z "$SCHEDULE" ]; then
        echo "Warning: mode '$MODE' is enabled but has no schedule. Skipping."
        continue
    fi

    ENTRY="$SCHEDULE . ~/.bash_profile 2>/dev/null; cd $PROJECT_DIR && $SCRIPT_DIR/run.sh $MODE >> $SCRIPT_DIR/logs/cron_${MODE}.log 2>&1"
    CRON_BLOCK="$CRON_BLOCK
$ENTRY"
    FOUND_ANY=true
done <<< "$MODES"

CRON_BLOCK="$CRON_BLOCK
$MARKER_END"

if [ "$FOUND_ANY" = false ]; then
    echo "No enabled modes with schedules found in config. Nothing to install."
    exit 0
fi

# ---------------------------------------------------------------------------
# Preview or install
# ---------------------------------------------------------------------------

echo "Cron entries to install:"
echo ""
echo "$CRON_BLOCK"
echo ""

if [ "$SHOW_ONLY" = true ]; then
    echo "(--show mode, no changes made)"
    exit 0
fi

# Remove any existing STEEX block, then append new one
EXISTING=$(crontab -l 2>/dev/null || true)

# Strip old block if present
CLEANED=$(echo "$EXISTING" | sed "/$MARKER_START/,/$MARKER_END/d")

# Append new block
NEW_CRONTAB="$CLEANED
$CRON_BLOCK"

# Trim leading blank lines
NEW_CRONTAB=$(echo "$NEW_CRONTAB" | sed '/./,$!d')

echo "$NEW_CRONTAB" | crontab -

echo "Cron entries installed. Verify with: crontab -l"
